### ISSUE TITLE
Fails on heroku-22 stack due to no system ruby

### ISSUE THREAD

**Issue by robotfelix** [heroku/heroku-buildpack-github-netrc#2]
This buildpack is failing at build time on the `heroku-22` stack with the error
```
-----> github-netrc app detected
/usr/bin/env: ‘ruby’: No such file or directory
```
This seems clearly related to the removal of a system ruby from the stack (https://devcenter.heroku.com/articles/heroku-22-stack).

It's not clear what the suggested resolution is, beyond rewriting the buildpack in a language other than ruby.

**Comment by edmorley** [comment]
@robotfelix Hi! Thank you for filing this issue :-)

For buildpacks written in Ruby the options to deal with no system Ruby, are:
1. Vendor Ruby
2. Add the Ruby buildpack prior to the buildpack that needs it (if possible; but as you say, not for this use-case)
3. Convert to bash

For the majority of buildpacks that aren't doing anything advanced, converting to bash will be the best option. A higher level language doesn't really add much value for such cases.

I've opened #3 to convert this buildpack to bash.
